name: Build Magisk Module

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Prepare Magisk module folder
        run: |
          mkdir flagsecure-disabler
          rsync -av --exclude='.git' --exclude='.github' --exclude='.DS_Store' ./ flagsecure-disabler/ --delete

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flagsecure-disabler
          path: flagsecure-disabler
          if-no-files-found: error
          retention-days: 90
